# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190827_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
